### ISSUE TITLE
Documentation doesn't exist on hexdocs

### ISSUE THREAD

**Issue by mcky** [djm/table_rex#1]
[http://hexdocs.pm/table_rex](http://hexdocs.pm/table_rex) returns a 404

**Comment by djm** [comment]
Ty, need to add a pre-release thing to the README. It's not quite ready for hex release yet.

**Comment by mcky** [comment]
Ah ok, perhaps add one of these when it is? :) ![Hex.pm](https://img.shields.io/hexpm/v/table_rex.svg)

**Comment by djm** [comment]
Yeah def. Needs setting up with CI too.

**Comment by djm** [comment]
Uploaded to Hex, Travis done, InchCI done and added that badge. Thank you Mr @mcky!
