### ISSUE TITLE
Breaking when the header is longer than the table is wide

### ISSUE THREAD

**Issue by boxxxie** [djm/table_rex#13]
this code throws an error
```
    TableRex.quick_render!([[300],[300]], ["passed", "failed"], "Test Results for Normal Couple")  
** (FunctionClauseError) no function clause matching in String.duplicate/2
    (elixir) lib/string.ex:1111: String.duplicate(" ", -6)
             lib/table_rex/renderer/text.ex:217: TableRex.Renderer.Text.do_render_cell/4
             lib/table_rex/renderer/text.ex:99: TableRex.Renderer.Text.render_title/1
             lib/table_rex/renderer/text.ex:67: TableRex.Renderer.Text.render/2
             lib/table_rex.ex:26: TableRex.quick_render!/3

```

**Comment by djm** [comment]
@boxxxie thanks for the report.

I'm interested to know what you think it should do in this scenario: is a nicer error message what you're after?

**Comment by djm** [comment]
Closing due to no reply.

**Comment by boxxxie** [comment]
imagine this happening in Excel. you write a long title for your header and then excel crashes. 

or in my case, the headers are programmatically generated, and for some reason my program crashes. 

really bad, I can't use this feature. there are many ways to handle this, crashing shouldn't be one. as a user I don't even know how to work around this problem.

**Comment by djm** [comment]
@boxxxie I breezed over this and completely misunderstood what it was about, my apologies.

You're right, this is not acceptable behaviour - reopening. We have some options:

* truncate the header to slightly less than the table width
* include the header width in the table width calculations and extend the padding in the cells to stretch it out.

I don't really have many data points on how people are using this - how would you prefer this was handled?

**Comment by boxxxie** [comment]
I assume the title is extremely important. so it should be printed out, and it shouldn't make the table look ugly. if table Rex could give some feedback or a function to the user for them to create headers, would be the most flexible option.

**Comment by andyl** [comment]
I also ran into this bug.  IMHO the correct behavior should be:
- make the table wider to accommodate the title width
- add padding to the cells as needed to make the column separators align

**Comment by djm** [comment]
Yup, agreed.

As an aside: this ticket is up for grabs if anyone wishes to tackle it.

**Comment by boxxxie** [comment]
In my program, i actually implemented a maximum width, and a recursive header shortening strategy + legend maker. so the user still has some control over how big the tables get, even without full control of the data they are making the tables from. 
how does something like that sound? how easy would it be to implement table building strategies into tableRex?

**Comment by djm** [comment]
It does sound good! But having 'a legend' does also sound out of scope for what I originally intended to be a very lightweight library to display simple tables. You're welcome to share your answer in a gist though.

For clarity in this ticket, the solution we're going with for whoever picks this up will be to include the title in the table width calculations. If it is longer than that of the width, then the cells will be padded out _equally_ until the title fits. As the columns are padded equally, it may mean that the total width then exceeds that of the original long title - but this is a better solution that unequally padding the columns.

**Comment by matt-harvey** [comment]
Hello. I've submitted a fix for this: https://github.com/djm/table_rex/pull/21

Happy to take on board any feedback or requests to edit the PR especially as I'm a bit of an Elixir noob.

**Comment by djm** [comment]
@matt-harvey Super appreciated Matt. I'm currently away traveling but I will look at the PR as soon as possible. Thanks!
