### ISSUE TITLE
unknown key :wrapped_lines for struct TableRex.Cell

### ISSUE THREAD

**Issue by sudochop** [djm/table_rex#45]
Just added `ecto_psql_extras 0.6` to my project which pulls in `table_rex 3.1.1`. I'm now getting this compilation error:

```
== Compilation error in file lib/table_rex/renderer/text.ex ==
** (CompileError) lib/table_rex/renderer/text.ex:282: unknown key :wrapped_lines for struct TableRex.Cell
    (elixir 1.11.4) src/elixir_fn.erl:15: anonymous fn/4 in :elixir_fn.expand/3
    (elixir 1.11.4) expanding macro: Kernel.|>/2
```

```
$ elixir --version
Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.11.4 (compiled with Erlang/OTP 23)
```

**Comment by djm** [comment]
@sudochop Happy to accept a PR to fix it, if you can find out what the problem is.

**Comment by sudochop** [comment]
Turns out another one of my dependencies hard copys your lib in to their project heh.. https://github.com/unnawut/licensir/tree/master/lib/table_rex

**Comment by djm** [comment]
Heh, thanks for clearing that up.
