### ISSUE TITLE
Support displaying empty rows

### ISSUE THREAD

**Issue by pallix** [djm/table_rex#48]
I'm displaying results coming from a database (`"select * ..."` more or less) but when the selection is empty, since it has no rows, TableRex cannot display it:

```
** (TableRex.Error) Table must have at least one row before being rendered
    (table_rex 3.1.1) lib/table_rex.ex:28: TableRex.quick_render!/3
```

It would be more consistent to display an empty table, that is just the header but no rows.

**Comment by djm** [comment]
Yes, I'd agree with that - happy to accept a PR that enables this /w a test.
