### ISSUE TITLE
Binary <<0>> messes up the layout

### ISSUE THREAD

**Issue by dkuku** [djm/table_rex#49]
I just got some bad data from the database and it's showing:
* as 2 chars in tests in terminal and it's too wide
* in livebook it's too narrow
```
  test "quick_render! with header and invalid rows" do
    rendered =
      TableRex.quick_render!(
        [
          [<<0, 0, 0>>, "Cyanide", 1999],
        ],
        ["Artist", "Track", "Year"]
      )

    assert rendered == """
           +--------+---------+------+
           | Artist | Track   | Year |
           +--------+---------+------+
           | \0\0\0    | Cyanide | 1999 |
           +--------+---------+------+
           """
  end
```

**Comment by djm** [comment]
This is library for rendering text and I'm not sure we should extend it to render binary.

What would the argument for doing this be? What's the value?

**Comment by dkuku** [comment]
I just got the from a db query. I'm playing around with postgres and
rendering the results. It's just a suggestion that I spotted.

**Comment by djm** [comment]
I'm closing this as `wontfix` for now but if there is enough support to fix it I am open to someone making the argument! 

Thanks.
