### ISSUE TITLE
Add support for multi-line cells.

### ISSUE THREAD

**Issue by djm** [djm/table_rex#7]
Support is already half baked in as row height counts are actually calculated.

However, the text renderer is not clever enough to render multiline yet as it works on a line per line basis.

This is a substantial piece of work.

**Comment by nguyenvinhlinh** [comment]
I will be very helpful, I did implement your table_rex multi-line cells is what I am looking for. 
https://github.com/nguyenvinhlinh/HexSearcher

**Comment by djm** [comment]
@nguyenvinhlinh Awesome that somebody is using it already.

I will prioritise this over other 1.0 milestones.

**Comment by djm** [comment]
Work on this is ongoing on the branch: `[feature/multiline-cells](https://github.com/djm/table_rex/tree/feature/multiline-cells)`.

**Comment by djm** [comment]
I don't have the time to work on this as much these days, if anyone would like to pick the branch up and run with it, they are more than welcome to.
