### ISSUE TITLE
TableRex.Renderer.Text.Meta.__struct__/1 is undefined, cannot expand struct TableRex.Renderer.Text.Meta

### ISSUE THREAD

**Issue by hojgr** [djm/table_rex#9]
Hello!

I wanted to use this library but I get this error

```
== Compilation error on file lib/table_rex/renderer/text.ex ==
** (CompileError) lib/table_rex/renderer/text.ex:53: TableRex.Renderer.Text.Meta.__struct__/1 is undefined, cannot expand struct TableRex.Renderer.Text.Meta
```

Is this library not compatible with Elixir 1.3?

Thanks

**Comment by djm** [comment]
Hi Michal,

That is a possibility as I hadn't got around to checking 1.3 yet but I
can't say for sure as I'm abroad at the moment. I'll take a look this
coming week when I'm back or you're welcome to look deeper at the issue in
the meantime.

Cheers!
Darian

**Comment by djm** [comment]
Closing due to #10. Thanks for the report.
